# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-14 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('username', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=60)),
                ('mode', models.NullBooleanField(verbose_name='mode:')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('Field_name', models.CharField(blank=True, choices=[('Cricket', 'Cricket'), ('Football', 'Football'), ('Tennis', 'Tennis'), ('VolleyBall', 'VolleyBall'), ('BasketBall', 'BasketBall'), ('Squash', 'Squash')], default=None, max_length=200, null=True)),
                ('purpose', models.TextField()),
                ('Booking_date', models.DateField()),
                ('Booking_time', models.TimeField()),
                ('pending', models.BooleanField(default=False)),
                ('approved_comment', models.BooleanField(default=False)),
            ],
        ),
    ]
